services:
  db:
    image: postgres:16
    ports:
      - '5432:5432'
    # Starts Postgres in non-durable mode which is faster
    command: postgres -c fsync=off -c synchronous_commit=off -c full_page_writes=off
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

volumes:
  postgres-data:

networks:
  default:
    name: npa-network
